### ISSUE TITLE
When switching to the lens, the default filters are not tightened

### ISSUE THREAD

**Issue by oleksandr-roskovynskyi** [dcasia/resource-navigation-link#2]
Nova v.2.12
LensResource

Cropped screenshot:
![image](https://user-images.githubusercontent.com/57599426/81093760-38e27980-8f0b-11ea-9c82-bc3dedab2c11.png)

Can you please help to make the default URL filters tweak?
Type this:
http://127.0.0.1:8000/nova/resources/balance-summaries/lens/balance-summary-by-months-by-company-lenses?balance-summaries_page=1&balance-summaries_filter=W3siY2xhc3MiOiJBcHBcXE5vdmFcXEZpbHRlcnNcXEJhbGFuY2VTdW1tYXJ5QnlEYXlMZW5zWWVhckZpbHRlciIsInZhbHVlIjoiMjAyMCJ9LHsiY2xhc3MiOiJBcHBcXE5vdmFcXEZpbHRlcnNcXENvbXBhbnlGaWx0ZXIiLCJ2YWx1ZSI6IiJ9LHsiY2xhc3MiOiJBcHBcXE5vdmFcXEZpbHRlcnNcXEJhbGFuY2VTdW1tYXJ5QnlEYXlMZW5zUFNIaXN0b3J5TXVsdGlTZWxlY3RGaWx0ZXIiLCJ2YWx1ZSI6W119LHsiY2xhc3MiOiJBcHBcXE5vdmFcXEZpbHRlcnNcXEN1cnJlbmN5RmlsdGVyIiwidmFsdWUiOiIifV0%3D

**Comment by milewski** [comment]
Sorry I dont understand what you mean? do you want the tab to carry over the query strings?

**Comment by oleksandr-roskovynskyi** [comment]
> Sorry I dont understand what you mean? do you want the tab to carry over the query strings?

No, when switching to a regular lens, the values of the filters from the current lens are automatically substituted in the query (present parameter when switching to the lens _filter =, with default values if any), and when switching to your filter library, the lenses are not automatically set (no parameter at going to lens_filter =)

**Comment by oleksandr-roskovynskyi** [comment]
The problem may be in the collisions on the frontend, not in your library, I found that the filter does not load for months, I will study this bug in more detail and write it off!

**Comment by oleksandr-roskovynskyi** [comment]
The problem arose due to an old version of the custom frontend component of the lens
