### ISSUE TITLE
Please add support for Nova 4

### ISSUE THREAD

**Issue by newtec-foggia** [dcasia/resource-navigation-link#24]
Hi,

Please add support for Nova 4.
Regards

**Comment by LorenzoSapora** [comment]
I'm not sure what's stopping this from being compliant with Nova 4.. If @milewski can point me at the issue, I'll write a PR.

**Comment by milewski** [comment]
Support added: [v1.0.0](https://github.com/dcasia/resource-navigation-link/releases/tag/v1.0.0)
