### ISSUE TITLE
Question: toFilter() support

### ISSUE THREAD

**Issue by ghost** [dcasia/resource-navigation-link#35]
Hi, we have a use case for filtering resources on an index view via tabs (navigation links). Do you have any plans for extending the functionality with toFilter() method? If not, would you consider accepting PR with the implementation? Thanks!

**Comment by milewski** [comment]
If I understood correctly do you mean like it would open an index page but with already some filters applied? which would be equivalent of having the url like: `/resources/users?users_filter=xxxxx`, sure go for it I can see it being simple to do also perhaps call it `toFilteredResoureIndex()`?

**Comment by ghost** [comment]
Hi @milewski. Colleague of mine has prepared the PR, please see https://github.com/dcasia/resource-navigation-link/pull/36.

**Comment by milewski** [comment]
Merged
